channels:
- conda-forge
dependencies:
- python=3.13.9
- pip<=25.3
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.2
  - psutil==7.1.3
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env